---
# tasks file for sa-jenkins-swarm-runner

  - block:

      - include: tasks_java.yml
        when: ansible_os_family != "Windows"

      - include: tasks_java_win.yml
        when: ansible_os_family == "Windows"

    when: option_install_java



  - include_tasks: tasks_swarm_agent.yml
